"""
paper_exp/make_final.py  —  ONE world builder for every paper experiment
========================================================================

Generated from v7_3's files (which already carry CF_LOOKBACK) by inserting code
at anchors that must each occur exactly once. With every knob at its default the
files behave exactly like v7_3 (checked by record identity before any run).

Knobs (environment variables, so all four shards of a run inherit them):

  SIM        learned (default)   the learned world model (v7.3)
             laws                v8's textbook laws fitted on TRAIN (v8/laws.json)
             straight            constant velocity, objects pass through each other
             straight_friction   the laws' friction only: no bounce
  NO_VOXEL=1   learned simulator without the voxel contact impulse
  NO_FORCE=1   learned simulator without the learned pair energy (forces zero;
               voxel impulse and learned friction stay)
  DRAG_SCALE   multiply the learned friction (1 = unchanged; eval-time only, the
               energy was trained together with friction)
  CF_LOOKBACK  hand-off look-ahead (v7_3's knob)

Evaluator flags kept from v7_3: --model, --no-entry-fix, --no-sim, --questions,
--which, --extend.

    python paper_exp/make_final.py
"""

import os
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HERE = os.path.join(ROOT, "paper_exp")
sys.path.insert(0, os.path.join(ROOT, "v8"))
from make_v8 import LAW_CODE                                           # noqa: E402

DOC = '''"""
paper_exp/cf_world.py  —  GENERATED by paper_exp/make_final.py from v7_3/cf_world.py.
Identical with default knobs. SIM swaps the simulator (learned | laws | straight |
straight_friction); NO_VOXEL, NO_FORCE and DRAG_SCALE ablate parts of the learned one.
"""
'''

SIMPLE_CODE = '''
def simple_step(mode, q_s, p_s, mass, ctx, N, friction):
    """Straight lines: every simulated object keeps its velocity (optionally slowed
    by the fitted friction law), and nothing bounces."""
    for k in range(N):
        if mode[k] != "sim":
            continue
        v = (p_s[k] / mass[0, k]).detach().numpy().astype(np.float64)
        if friction:
            L = ctx["motion"].get(ctx["kinds"][k], {"chosen": "const", "param": 0.0})
            if L["chosen"] == "exp":
                v = v * (1.0 - L["param"])
            elif L["chosen"] == "coul":
                s = float(np.linalg.norm(v))
                v = v * (max(s - L["param"], 0.0) / max(s, 1e-12))
        q_s[k] = torch.from_numpy((q_s[k].numpy().astype(np.float64) + v).astype(np.float32))
        p_s[k] = mass[0, k].detach() * torch.from_numpy(v.astype(np.float32))


'''


def once(text, anchor, what):
    n = text.count(anchor)
    if n != 1:
        raise SystemExit("anchor for %s found %d times, expected 1" % (what, n))


def main():
    os.makedirs(HERE, exist_ok=True)
    src = open(os.path.join(ROOT, "v7_3", "cf_world.py"), encoding="utf-8").read()
    knob_anchor = "PHYS_RADIUS_SCALE = float(_os_v73.environ.get(\"PHYS_RADIUS_SCALE\", \"1.0\"))\n"
    ctx_anchor = "    contact = r[:, None] + r[None, :]\n"
    step_anchor = "        # ---- advance the simulated objects one frame ------------------------------\n"
    vox_anchor = ("            p, _ = resolve_voxel(q, p, mass, radius, act, attrs[:N, 1], shapes,\n"
                  "                                 yaw[0].detach().cpu().numpy())\n")
    def_anchor = "def build_world(model, z, removed"
    for a, w in ((knob_anchor, "knobs"), (ctx_anchor, "contact line"), (step_anchor, "advance block"),
                 (vox_anchor, "voxel impulse"), (def_anchor, "build_world definition")):
        once(src, a, w)
    src = src.replace(knob_anchor, knob_anchor +
                      "SIM = _os_v73.environ.get(\"SIM\", \"learned\")\n"
                      "NO_VOXEL = _os_v73.environ.get(\"NO_VOXEL\", \"0\") == \"1\"\n"
                      "if SIM not in (\"learned\", \"laws\", \"straight\", \"straight_friction\"):\n"
                      "    raise SystemExit(\"unknown SIM=%s\" % SIM)\n"
                      "LAWS = None\n"
                      "if SIM in (\"laws\", \"straight_friction\"):\n"
                      "    import json as _json_f\n"
                      "    LAWS = _json_f.load(open(_os_v73.path.join(_os_v73.path.dirname(_os_v73.path.dirname(\n"
                      "        _os_v73.path.abspath(__file__))), \"v8\", \"laws.json\")))\n")
    src = src.replace(ctx_anchor, ctx_anchor +
                      "    law_ctx = make_law_context(z, shapes, N, LAWS) if LAWS is not None else None\n")
    src = src.replace(step_anchor, step_anchor +
                      "        if t < TT - 1 and SIM != \"learned\" and any(m_ == \"sim\" for m_ in mode):\n"
                      "            if SIM == \"laws\":\n"
                      "                law_step(t, mode, M, pos, vel, q_s, p_s, mass, law_ctx, N)\n"
                      "            else:\n"
                      "                simple_step(mode, q_s, p_s, mass, law_ctx, N, SIM == \"straight_friction\")\n"
                      "            for k in range(N):\n"
                      "                if mode[k] == \"sim\" and float(q_s[k].abs().max()) > TABLE_EXTENT:\n"
                      "                    mode[k] = \"gone\"\n"
                      "            continue\n")
    src = src.replace(vox_anchor,
                      "            if not NO_VOXEL:\n"
                      "                p, _ = resolve_voxel(q, p, mass, radius, act, attrs[:N, 1], shapes,\n"
                      "                                     yaw[0].detach().cpu().numpy())\n")
    src = src.replace(def_anchor, LAW_CODE.lstrip("\n") + SIMPLE_CODE.lstrip("\n") + def_anchor)
    open(os.path.join(HERE, "cf_world.py"), "w", encoding="utf-8").write(DOC + src)

    ev = open(os.path.join(ROOT, "v7_3", "evaluate.py"), encoding="utf-8").read()
    load_anchor = "    model = load_spatial(a.model, yaw_known=False)\n"
    once(ev, 'os.path.join(HERE, "cf_world.py")', "cf_world import through HERE")
    once(ev, load_anchor, "model load")
    ev = ev.replace(load_anchor, load_anchor +
                    "    _ds = float(os.environ.get(\"DRAG_SCALE\", \"1\"))\n"
                    "    if _ds != 1.0:\n"
                    "        # eval-time ablation: scale the learned friction (same patch as app/intervene.friction)\n"
                    "        _cls = type(model)\n"
                    "        model.drag_coeff = lambda e_, pr_: (lambda c_: None if c_ is None else c_ * _ds)(_cls.drag_coeff(model, e_, pr_))\n"
                    "        model.rot_drag_coeff = lambda e_, pr_: (lambda c_: None if c_ is None else c_ * _ds)(_cls.rot_drag_coeff(model, e_, pr_))\n"
                    "    if os.environ.get(\"NO_FORCE\", \"0\") == \"1\":\n"
                    "        # ablation: switch the learned pair energy off (no forces, no torques)\n"
                    "        model.forces_torques = lambda q_, yaw_, *r_, **k_: (torch.zeros_like(q_), torch.zeros_like(yaw_))\n"
                    "    print(\"knobs: SIM=%s CF_LOOKBACK=%s NO_VOXEL=%s NO_FORCE=%s DRAG_SCALE=%s model=%s entry_fix=%s\" % (\n"
                    "        os.environ.get(\"SIM\", \"learned\"), os.environ.get(\"CF_LOOKBACK\", \"12\"),\n"
                    "        os.environ.get(\"NO_VOXEL\", \"0\"), os.environ.get(\"NO_FORCE\", \"0\"), _ds, a.model,\n"
                    "        not a.no_entry_fix), flush=True)\n")
    # EVERY option is scored. With detection-only tracks an object named in a question
    # can be missing (missed or mislabelled by the detector); such options used to be
    # skipped. Now they are written with empty event lists (answer: "does not collide"),
    # and an unresolved removed object means nothing is removed.
    for old, new, what in (
            ("        if not qd:\n            continue\n",
             "", "program parse"),
            ("        removed = set(k for k in resolve_all(qd[0], keys) if k < N)\n",
             "        removed = set(k for k in resolve_all(qd[0], keys) if k < N) if qd else set()\n", "removed line"),
            ("        if not removed:\n            continue\n",
             "        removed_unresolved = not removed\n", "removed object"),
            ("            if len(cd) < 2:\n                continue\n",
             "            unresolved = len(cd) < 2\n", "choice parse"),
            ("            h1 = [k for k in resolve_all(cd[0], keys) if k < N]\n"
             "            h2 = [k for k in resolve_all(cd[1], keys) if k < N]\n"
             "            if len(h1) != 1 or len(h2) != 1 or h1[0] == h2[0]:\n"
             "                continue\n"
             "            i, j = sorted((h1[0], h2[0]))\n",
             "            h1 = [] if unresolved else [k for k in resolve_all(cd[0], keys) if k < N]\n"
             "            h2 = [] if unresolved else [k for k in resolve_all(cd[1], keys) if k < N]\n"
             "            unresolved = len(h1) != 1 or len(h2) != 1 or h1[0] == h2[0]\n"
             "            i, j = sorted((h1[0], h2[0])) if not unresolved else (-1, -2)\n", "choice objects"),
            ("                   \"i\": i, \"j\": j, \"removed\": sorted(removed), \"T\": w[\"T\"],\n",
             "                   \"i\": i, \"j\": j, \"removed\": sorted(removed), \"T\": w[\"T\"],\n"
             "                   \"unresolved\": bool(unresolved), \"removed_unresolved\": bool(removed_unresolved),\n",
             "record fields")):
        once(ev, old, what)
        ev = ev.replace(old, new)
    # PARSED=1: programs come from the question TEXT (paper_exp/qparser.py, fitted on
    # TRAIN questions), not from the dataset's ground-truth programs
    rows_anchor = "    rows = load_questions(a.questions)\n"
    once(ev, rows_anchor, "question load")
    ev = ev.replace(rows_anchor, rows_anchor +
                    "    if os.environ.get(\"PARSED\", \"0\") == \"1\":\n"
                    "        sys.path.insert(0, HERE)\n"
                    "        import qparser as _qp\n"
                    "        for r_ in rows:\n"
                    "            r_[\"program\"] = _qp.parse(r_.get(\"question\", \"\")) or []\n"
                    "            ch_ = r_.get(\"choices\")\n"
                    "            if isinstance(ch_, dict) and ch_.get(\"program\"):\n"
                    "                ch_[\"program\"] = [(_qp.parse(t_) or []) for t_ in ch_[\"choice\"]]\n"
                    "        print(\"programs parsed from question text\", flush=True)\n")
    ev = '"""\npaper_exp/evaluate.py  —  GENERATED by paper_exp/make_final.py from v7_3/evaluate.py.\n"""\n' + ev
    open(os.path.join(HERE, "evaluate.py"), "w", encoding="utf-8").write(ev)
    shutil.copy(os.path.join(ROOT, "v7_3", "entry_profile.json"), os.path.join(HERE, "entry_profile.json"))
    print("wrote paper_exp/cf_world.py, evaluate.py, entry_profile.json")


if __name__ == "__main__":
    main()
