"""
v7_1/make_v7_1.py  —  build v7.1 = v7's learned world model + the entry-state correction
=======================================================================================

v7.1 keeps EVERYTHING of v7 -- the learned world model simulating with voxel
bounces, the influence rules, +frames past the video end, the detectors -- and
changes ONE thing: the starting state of an object handed to the simulator
within 15 frames of entering the scene.

Why (measured by replaying real videos, probe/shadow_replay.py): an object
sliding into view is only partly visible, so its measured centre sits ~2.5 steps
ahead of the true centre and its speed reads ~70% of the real speed for ~8
frames. v7's learned model and v8's laws both broke on this the same way; it is
a data problem. The correction divides the speed by the measured ratio and moves
the start back by the measured lag, both from TRAIN videos only
(entry_profile.json), using no future frames.

Files are GENERATED from v7's by inserting at anchors that must each occur once,
so nothing of v7 is retyped.

    python v7_1/make_v7_1.py
"""

import os
import shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HERE = os.path.join(ROOT, "v7_1")

WORLD_DOC = '''"""
v7_1/cf_world.py  —  v7's "what if" world builder + entry-state correction
===========================================================================
GENERATED by v7_1/make_v7_1.py from v7/cf_world.py. Identical to v7 except
build_world(..., entry_fix=profile) corrects the starting state of objects handed
to the learned world model within len(profile["ratio"]) frames of entering.
With entry_fix=None it is exactly v7. v7's own description follows.
"""
'''


def once(text, anchor, what):
    n = text.count(anchor)
    if n != 1:
        raise SystemExit("anchor for %s found %d times, expected 1" % (what, n))


def main():
    src = open(os.path.join(ROOT, "v7", "cf_world.py"), encoding="utf-8").read()
    sig_old = "influence=True, sizes=None, dynamics_sizes=False):"
    sig_new = "influence=True, sizes=None, dynamics_sizes=False, entry_fix=None):"
    tosim_anchor = ("        q_s[k] = torch.from_numpy(pos[t, k])\n"
                    "        p_s[k] = mass[0, k] * torch.from_numpy(np.asarray(v0, np.float32))\n")
    tosim_new = ("        p0 = pos[t, k].astype(np.float64)\n"
                 "        if entry_fix is not None:\n"
                 "            # an object still sliding into view is measured too SLOW and too far AHEAD\n"
                 "            # (the visible part's centre): undo both with the TRAIN entry profile\n"
                 "            on_ = np.where(pres[:, k] > 0)[0]\n"
                 "            e0 = int(on_[0]) if on_.size else 0\n"
                 "            tau = t - e0\n"
                 "            if e0 > 0 and 0 <= tau < len(entry_fix[\"ratio\"]):\n"
                 "                v0 = np.asarray(v0, np.float64) / max(entry_fix[\"ratio\"][tau], 0.3)\n"
                 "                p0 = p0 - entry_fix[\"lag\"][tau] * v0\n"
                 "        q_s[k] = torch.from_numpy(p0.astype(np.float32))\n"
                 "        p_s[k] = mass[0, k] * torch.from_numpy(np.asarray(v0, np.float32))\n")
    once(src, sig_old, "signature")
    once(src, tosim_anchor, "to_sim start state")
    src = src.replace(sig_old, sig_new).replace(tosim_anchor, tosim_new)
    open(os.path.join(HERE, "cf_world.py"), "w", encoding="utf-8").write(WORLD_DOC + src)

    ev = open(os.path.join(ROOT, "v7", "evaluate.py"), encoding="utf-8").read()
    imp_old = "from cf_world import build_world                                         # noqa: E402\n"
    imp_new = ("import importlib.util                                                    # noqa: E402\n"
               "_spec = importlib.util.spec_from_file_location(\"v7_1_cf_world\", os.path.join(HERE, \"cf_world.py\"))\n"
               "_cfw = importlib.util.module_from_spec(_spec)\n"
               "_spec.loader.exec_module(_cfw)\n"
               "build_world = _cfw.build_world\n")
    arg_old = "    ap.add_argument(\"--shard\", type=int, default=0)\n"
    arg_new = ("    ap.add_argument(\"--no-entry-fix\", action=\"store_true\",\n"
               "                    help=\"turn the entry correction OFF (then this is exactly v7)\")\n" + arg_old)
    thr_old = "    torch.set_num_threads(1)\n"
    thr_new = thr_old + ("    ENTRY = None if a.no_entry_fix else json.load(open(os.path.join(HERE, \"entry_profile.json\")))\n")
    call_old = "                                     dynamics_sizes=a.dynamics_sizes)"
    call_new = "                                     dynamics_sizes=a.dynamics_sizes, entry_fix=ENTRY)"
    for a, w in ((imp_old, "import"), (arg_old, "--shard arg"), (thr_old, "thread line"), (call_old, "build_world call")):
        once(ev, a, w)
    ev = ev.replace(imp_old, imp_new).replace(arg_old, arg_new).replace(thr_old, thr_new).replace(call_old, call_new)
    doc = ('"""\nv7_1/evaluate.py  —  GENERATED by v7_1/make_v7_1.py from v7/evaluate.py. Identical except\n'
           'the entry correction is ON (use --no-entry-fix for plain v7). v7/report.py scores the records.\n"""\n')
    open(os.path.join(HERE, "evaluate.py"), "w", encoding="utf-8").write(doc + ev)
    shutil.copy(os.path.join(ROOT, "v8", "entry_profile.json"), os.path.join(HERE, "entry_profile.json"))
    print("wrote v7_1/cf_world.py, v7_1/evaluate.py, v7_1/entry_profile.json")


if __name__ == "__main__":
    main()
