"""
v7_1_oracle/make_oracle.py  —  CEILING PROBE for a learned state estimator (the temporal-GNN idea)
==================================================================================================

In the jet project a temporal graph network paid off because every missile hides different
settings (turn rate, lead, datalink) and the world model is exact once it knows them: oracle
42/48 matches vs no GNN 22/48. On CLEVRER the objects hide almost nothing (the fitted laws found
one bounciness for every pair and a metal/rubber mass ratio of 1.0). The one thing that IS hidden
is each object's true current motion at the moment it is handed to the simulator: tracks are
noisy, and objects sliding into view are measured wrong.

Before building a TGN to infer that from the past, measure the best case. With ORACLE_HANDOFF=1
the hand-off state is a straight-line fit to the recorded track INCLUDING FUTURE FRAMES (frames
t-3 .. t+8, stopping 2 frames before the next recorded contact, starting 3 frames after the last
one, skipping the first 10 biased frames after an entry, extrapolated to frame t). A method that
only sees the past cannot do much better than this.

If VAL barely moves with the oracle, no state estimator (TGN or otherwise) can move the benchmark.
This is a ceiling only: it uses future frames and must never be reported as a result.

Generated from v7_1 like make_v7_1.py: the ONLY change is the hand-off state, and only when
ORACLE_HANDOFF=1. With the variable unset the files behave exactly like v7.1.

    python v7_1_oracle/make_oracle.py
"""

import os
import shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HERE = os.path.join(ROOT, "v7_1_oracle")

DOC = '''"""
v7_1_oracle/cf_world.py  —  GENERATED by v7_1_oracle/make_oracle.py from v7_1/cf_world.py.
Identical except: with ORACLE_HANDOFF=1 the hand-off state uses FUTURE recorded frames
(ceiling probe for a learned state estimator; never a reportable result).
"""
'''

ORACLE_CODE = '''
# ============================================================================
# CEILING PROBE: oracle hand-off state from future recorded frames
# ============================================================================
import os as _os_oracle
ORACLE_HANDOFF = _os_oracle.environ.get("ORACLE_HANDOFF", "0") == "1"
ORACLE_STATS = {"used": 0, "fallback": 0}
if ORACLE_HANDOFF:
    import atexit as _atexit_oracle
    _atexit_oracle.register(lambda: print("ORACLE_STATS %s" % ORACLE_STATS, flush=True))


def _oracle_state(pos, pres, obs_contact, k, t, T, before=3, after=8, skip_entry=10, min_frames=4):
    """Best-case state of object k at frame t: a least-squares line through its recorded
    positions around t (future frames included), clear of recorded contacts and of the biased
    frames just after it entered. Returns (position at t, velocity) or None."""
    on = np.where(pres[:, k] > 0)[0]
    if not on.size:
        return None
    e0 = int(on[0])
    hits = sorted(int(h) for (a, b), hh in obs_contact.items() if a == k for h in hh)
    prev = [h for h in hits if h < t]
    nxt = [h for h in hits if h >= t]
    lo = t - before
    if prev:
        lo = max(lo, prev[-1] + 3)
    if e0 > 0:
        lo = max(lo, e0 + skip_entry)
    hi = min(T - 1, t + after, (nxt[0] - 2) if nxt else T - 1)
    us = [u for u in range(max(lo, 0), hi + 1) if pres[u, k] > 0]
    if len(us) < min_frames:
        return None
    u = np.asarray(us, np.float64) - t
    P = pos[us, k].astype(np.float64)
    A = np.stack([np.ones_like(u), u], 1)
    coef = np.linalg.lstsq(A, P, rcond=None)[0]
    return coef[0], coef[1]


'''

ORACLE_HOOK = ('        if ORACLE_HANDOFF:\n'
               '            _o = _oracle_state(pos, pres, obs_contact, k, t, T)\n'
               '            if _o is None:\n'
               '                ORACLE_STATS["fallback"] += 1\n'
               '            else:\n'
               '                p0, v0 = _o\n'
               '                ORACLE_STATS["used"] += 1\n')


def once(text, anchor, what):
    n = text.count(anchor)
    if n != 1:
        raise SystemExit("anchor for %s found %d times, expected 1" % (what, n))


def main():
    os.makedirs(HERE, exist_ok=True)
    src = open(os.path.join(ROOT, "v7_1", "cf_world.py"), encoding="utf-8").read()
    def_anchor = "def build_world("
    tosim_anchor = ("        q_s[k] = torch.from_numpy(p0.astype(np.float32))\n"
                    "        p_s[k] = mass[0, k] * torch.from_numpy(np.asarray(v0, np.float32))\n")
    once(src, def_anchor, "build_world definition")
    once(src, tosim_anchor, "to_sim start state")
    for name in ("obs_contact = {}", "pres = z[\"presence\"]", "T = pos.shape[0]"):
        if name not in src:
            raise SystemExit("expected closure variable missing: %s" % name)
    src = src.replace(tosim_anchor, ORACLE_HOOK + tosim_anchor)
    src = src.replace(def_anchor, ORACLE_CODE.lstrip("\n") + def_anchor)
    open(os.path.join(HERE, "cf_world.py"), "w", encoding="utf-8").write(DOC + src)

    ev = open(os.path.join(ROOT, "v7_1", "evaluate.py"), encoding="utf-8").read()
    once(ev, 'os.path.join(HERE, "cf_world.py")', "cf_world import through HERE")
    open(os.path.join(HERE, "evaluate.py"), "w", encoding="utf-8").write(ev)
    shutil.copy(os.path.join(ROOT, "v7_1", "entry_profile.json"), os.path.join(HERE, "entry_profile.json"))
    print("wrote v7_1_oracle/cf_world.py, evaluate.py, entry_profile.json")


if __name__ == "__main__":
    main()
