"""
v7_3/make_v7_3.py  —  two knobs on top of v7.1, both OFF by default
====================================================================

Generated from v7_1 exactly like make_v7_1.py (insert at anchors that must each
occur once). With neither environment variable set, the files behave exactly
like v7.1 (checked by records identity before any run).

PHYS_RADIUS_SCALE  (default 1.0)
    Multiplies the radius the WORLD MODEL simulates with (the learned energy's
    contact distance, the voxel contact shells, the inertia) and nothing else.
    The collision detector keeps reading the stored sizes. With 1.2, the physics
    uses the same enlarged size the calibrated detector already uses, so the two
    finally agree: the question was "one size for both".

CF_LOOKBACK  (default 12)
    How many frames before an expected, no-longer-valid recorded contact an object
    is handed to the world model. v7 has always used 12. Swept on VAL only.

    python v7_3/make_v7_3.py
"""

import os
import shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HERE = os.path.join(ROOT, "v7_3")

DOC = '''"""
v7_3/cf_world.py  —  GENERATED by v7_3/make_v7_3.py from v7_1/cf_world.py.
Identical except two environment knobs, both off by default:
PHYS_RADIUS_SCALE (physics radius only) and CF_LOOKBACK (hand-off look-ahead).
"""
'''


def once(text, anchor, what):
    n = text.count(anchor)
    if n != 1:
        raise SystemExit("anchor for %s found %d times, expected 1" % (what, n))


def main():
    os.makedirs(HERE, exist_ok=True)
    src = open(os.path.join(ROOT, "v7_1", "cf_world.py"), encoding="utf-8").read()
    lb_anchor = "LOOKBACK = 12\n"
    ph_anchor = "        mass, radius, e = model.properties(phys)\n"
    once(src, lb_anchor, "LOOKBACK constant")
    once(src, ph_anchor, "physics radius")
    src = src.replace(lb_anchor,
                      "import os as _os_v73\n"
                      "LOOKBACK = int(_os_v73.environ.get(\"CF_LOOKBACK\", \"12\"))\n"
                      "PHYS_RADIUS_SCALE = float(_os_v73.environ.get(\"PHYS_RADIUS_SCALE\", \"1.0\"))\n")
    src = src.replace(ph_anchor, ph_anchor +
                      "    if PHYS_RADIUS_SCALE != 1.0:\n"
                      "        # the world model simulates with this size; the detector keeps the stored one\n"
                      "        radius = radius * PHYS_RADIUS_SCALE\n")
    open(os.path.join(HERE, "cf_world.py"), "w", encoding="utf-8").write(DOC + src)

    ev = open(os.path.join(ROOT, "v7_1", "evaluate.py"), encoding="utf-8").read()
    once(ev, 'os.path.join(HERE, "cf_world.py")', "cf_world import through HERE")
    open(os.path.join(HERE, "evaluate.py"), "w", encoding="utf-8").write(ev)
    shutil.copy(os.path.join(ROOT, "v7_1", "entry_profile.json"), os.path.join(HERE, "entry_profile.json"))
    print("wrote v7_3/cf_world.py, evaluate.py, entry_profile.json")


if __name__ == "__main__":
    main()
