"""
v8/cf_world.py  —  v7's "what if" world builder, simulated by TEXTBOOK LAWS
===========================================================================
GENERATED by v8/make_v8.py from v7/cf_world.py. Identical to v7 except the
simulator: pass laws=json.load(open("v8/laws.json")) and every simulated object
is advanced by the fitted laws (law_step) instead of the learned world model.
Without laws=... it behaves exactly like v7. v7's own description follows.
"""
"""
v7/cf_world.py  —  intervene once, simulate the whole counterfactual scene, store every event
============================================================================================

HOW THIS DIFFERS FROM v5/v6
---------------------------
v5/v6 simulated each asked PAIR separately, in a window chosen per pair ("a few
frames before the pair's closest approach", or "from the pair's cone entry to
the end"). A per-choice diagnosis of all 3328 test choices showed that 610 of
the 799 missed collisions came from that windowing, not from physics:

  239  the pair collided BEFORE its window started (never simulated)
  183  one of the pair entered the scene after the window started, and the
       simulation refused to run
  188  the pair was treated as unaffected and only its observed closest
       approach was examined, although the collision happens elsewhere

This file does what published CLEVRER world models do (VRDP: "removes the
object and reruns the simulation"): ONE counterfactual world per intervention,
every object, every frame, and every choice is read off that single stored world.

THE WORLD, FRAME BY FRAME
-------------------------
Each object is in one of three states:
  absent   not on the table yet (or removed -- the intervention)
  video    following its recorded motion
  sim      free-running in the world model

An object enters when it first appears in the recording, with its recorded
position and velocity -- a boundary condition, exactly as new objects enter any
simulator. It FOLLOWS the recording only while nothing the intervention changed
can have reached it. That is causality, not a shortcut: before the removed
object's influence arrives, an object's counterfactual path IS its recorded
path. The moment influence can arrive, it is simulated, and from then on the
world model decides everything. Influence arrives when:

  (a) LOST CONTACT     in the recording, k is about to touch an object whose path
                       no longer exists -- the removed object, or any object
                       already being simulated -- so k's recorded motion after
                       that touch is invalid. k is simulated from LOOKBACK frames
                       before that touch.
  (b) NEW CONTACT      a simulated object comes near k's position.

(a) is decided from the recorded positions with the contact rule calibrated on
VAL (radius x1.20, +0.03: detects 98.3% of annotated collisions). No collision
annotation is read anywhere.

v5's cone had (a) only for the REMOVED object, and read it from the ground-truth
collision list. Measured: 31 of the 188 "treated as unaffected" misses were
pairs knocked in the recording by an object that was already being simulated.

  strict=True  every object is simulated from the frame it enters: initial
               conditions and entries only, no recorded motion after entry.

PAST THE END OF THE VIDEO
-------------------------
CLEVRER clips are 127 frames, and its predictive questions are explicitly about
collisions after the video ends. At the last recorded frame every object still
following the recording is handed to the simulator, which runs `extend` more
frames. Events carry their frame, so a shorter extension can be scored from the
same run by ignoring later events.

EVENTS
------
For every pair, at every frame both are on the table, three detectors are
logged, so the choice between them is made on VAL without re-simulating:
  rule   centre distance - (r_i + r_j) <= 0.02, approaching, hysteresis
  cal    same with radius x1.20 and 0.03 (the VAL calibration)
  voxel  lattice distance between the two objects' surface voxels, stored per
         frame whenever it is <= 12 voxels (0 = they press the same voxel)
"""

import math

import numpy as np
import torch

from world import strip_colour
from resolve import resolve_voxel
from diagnose import voxel_gap, shape_name

# same values as v5/evaluate.py. Defined here, not imported: v7/evaluate.py
# shadows that module name on the path and the import would be circular.
TABLE_EXTENT = 0.95


def _wrap_q(a):
    q = math.pi / 2
    return (a + q / 2) % q - q / 2

THRESH, RELEASE = 0.02, 0.02
CAL_SCALE, CAL_THRESH = 1.20, 0.03
MARGIN = 0.06
# "a collision changes someone's path": a pair counts as colliding when its
# surfaces come within KICK_GAP AND either object's velocity changes sharply
# nearby. For simulated objects that velocity change is the world model's own
# bounce. Measured on VAL recorded motion: removes ~20-40% of made-up
# collisions (near passes that never touched) at almost no loss of real ones.
KICK_GAP = 0.03
LOOKBACK = 12
VEL_SMOOTH = 3
NEAR_KEEP = 12.0
PREFILTER = 0.20


# ============================================================================
# v8: THE TEXTBOOK-LAW SIMULATOR (replaces the learned world model's step)
# ============================================================================
LAW_GAP_DEFAULT = 0.01


def make_law_context(z, shapes, N, laws):
    """Per-object facts the laws need: material, kind, contact size."""
    keys = [str(k) for k in z["obj_keys"]][:N]
    mats = [k.split("_")[1] for k in keys]
    col = laws["collision"]
    return {"mats": mats, "kinds": ["%s/%s" % (shapes[k], mats[k]) for k in range(N)],
            "sizes": np.array([laws["contact_sizes"][shapes[k]] for k in range(N)], np.float64),
            "motion": laws["motion"], "ratio": float(col["mass_ratio"]), "e": col["e"],
            "mu": float(col["mu"]), "gap": float(laws.get("contact_gap", LAW_GAP_DEFAULT))}


def law_step(t, mode, M, pos, vel, q_s, p_s, mass, ctx, N):
    """One frame for every simulated object, by the fitted laws.

    1. BOUNCE: every approaching pair whose surfaces are within ctx['gap'] gets
       the textbook impulse along the line of centres, J = -(1+e)(v_rel.n) /
       (1/m_i + 1/m_j), plus sliding friction at the contact. Equal and
       opposite, so momentum is conserved. Objects still following the video
       take part (their own recorded motion is not overwritten).
    2. MOTION LAW: each simulated object's speed shrinks by its kind's law --
       a fixed amount per frame (sliding) or a fixed percentage (rolling).
    3. MOVE: position += velocity.
    """
    idx = [k for k in range(N) if mode[k] == "sim" or M[t, k] == 1]
    P, V = {}, {}
    for k in idx:
        if mode[k] == "sim":
            P[k] = q_s[k].numpy().astype(np.float64)
            V[k] = (p_s[k] / mass[0, k]).detach().numpy().astype(np.float64)
        else:
            P[k] = pos[t, k].astype(np.float64)
            V[k] = vel[t, k].astype(np.float64)
    sizes, mats = ctx["sizes"], ctx["mats"]
    for a in range(len(idx)):
        for b in range(a + 1, len(idx)):
            i, j = idx[a], idx[b]
            if mode[i] != "sim" and mode[j] != "sim":
                continue
            d = P[i] - P[j]
            dist = float(np.linalg.norm(d))
            if dist < 1e-9 or dist - (sizes[i] + sizes[j]) > ctx["gap"]:
                continue
            vrel = V[i] - V[j]
            if float(vrel @ d) >= 0:
                continue
            n = d / dist
            vn = float(vrel @ n)
            mi = ctx["ratio"] if mats[i] == "metal" else 1.0
            mj = ctx["ratio"] if mats[j] == "metal" else 1.0
            cls = "".join(sorted(("m" if mats[i] == "metal" else "r") + ("m" if mats[j] == "metal" else "r")))
            e = float(ctx["e"][cls])
            inv = 1.0 / mi + 1.0 / mj
            Jn = -(1.0 + e) * vn / inv
            V[i] = V[i] + (Jn / mi) * n
            V[j] = V[j] - (Jn / mj) * n
            if ctx["mu"] > 0:
                vt = vrel - vn * n
                vtn = float(np.linalg.norm(vt))
                if vtn > 1e-12:
                    tv = vt / vtn
                    Jt = min(ctx["mu"] * Jn, vtn / inv)
                    V[i] = V[i] - (Jt / mi) * tv
                    V[j] = V[j] + (Jt / mj) * tv
    for k in idx:
        if mode[k] != "sim":
            continue
        L = ctx["motion"].get(ctx["kinds"][k], {"chosen": "const", "param": 0.0})
        v = V[k]
        if L["chosen"] == "exp":
            v = v * (1.0 - L["param"])
        elif L["chosen"] == "coul":
            s = float(np.linalg.norm(v))
            v = v * (max(s - L["param"], 0.0) / max(s, 1e-12))
        q_s[k] = torch.from_numpy((P[k] + v).astype(np.float32))
        p_s[k] = mass[0, k].detach() * torch.from_numpy(v.astype(np.float32))


def build_world(model, z, removed, extend=60, lost_contact_affected=True, strict=False,
                influence=True, sizes=None, dynamics_sizes=False, laws=None, entry_fix=None):
    """influence=False with extend=0 is the NO-SIMULATION baseline: the removed
    object is deleted and every other object keeps its recorded motion. It
    measures what reading the video alone scores, so the world model's own
    contribution can be stated."""
    pos = z["positions"].astype(np.float32); vel = z["velocities"].astype(np.float32)
    pres = z["presence"]; attrs = z["attrs"].astype(np.float32)
    yaw_d = z["yaw"].astype(np.float32) if "yaw" in z else np.zeros(pres.shape, np.float32)
    T = pos.shape[0]; N = min(8, pos.shape[1])
    removed = set(k for k in removed if k < N)
    shapes = [shape_name(attrs, k) for k in range(N)]
    r = attrs[:N, 15].copy()
    if sizes is not None:
        # MEASURED contact sizes (v7/measured_sizes.json): at 7,340 annotated
        # collisions in TRAIN videos the centre distance equals r_i + r_j, so a
        # least-squares fit over shape pairs gives each shape's true reach.
        # sphere x1.00, cylinder x1.03, cube x1.11 of the stored value.
        r = np.array([sizes[s] for s in shapes], np.float32)
        if dynamics_sizes:                      # also hand them to the world model
            attrs = attrs.copy(); attrs[:N, 15] = r
    at = torch.from_numpy(attrs[:N]).unsqueeze(0); phys = strip_colour(at)
    with torch.no_grad():
        mass, radius, e = model.properties(phys)
    I = model.inertia(phys, mass, radius)
    contact = r[:, None] + r[None, :]
    law_ctx = make_law_context(z, shapes, N, laws) if laws is not None else None
    TT = T + extend

    # recorded contacts, calibrated rule, for the lost-contact test (a)
    obs_contact = {}
    for k in range(N):
        for m in range(N):
            if k == m:
                continue
            both = (pres[:, k] > 0) & (pres[:, m] > 0)
            if not both.any():
                continue
            d = np.linalg.norm(pos[:, k] - pos[:, m], axis=-1)
            hit = np.where(both & (d - CAL_SCALE * contact[k, m] <= CAL_THRESH))[0]
            if hit.size:
                obs_contact[(k, m)] = hit

    mode = ["absent"] * N
    taint = {}                                     # k -> (frame, cause, other)
    q_s = torch.zeros(N, 2); p_s = torch.zeros(N, 2)
    y_s = torch.zeros(N); L_s = torch.zeros(N)
    P = np.full((TT, N, 2), np.nan, np.float32)
    V = np.full((TT, N, 2), np.nan, np.float32)     # velocity: recorded or the model's own
    M = np.zeros((TT, N), np.int8)                  # 0 absent, 1 video, 2 sim
    changed = set(removed)                          # objects whose recorded path no longer holds

    def to_sim(k, t, cause, other):
        vs = [vel[u, k] for u in range(max(0, t - VEL_SMOOTH + 1), t + 1) if pres[u, k] > 0]
        v0 = np.mean(vs, axis=0) if vs else vel[t, k]
        p0 = pos[t, k].astype(np.float64)
        if entry_fix is not None:
            # an object still sliding into view is measured too SLOW and too far AHEAD
            # (the visible part's centre): undo both with the TRAIN entry profile
            on_ = np.where(pres[:, k] > 0)[0]
            e0 = int(on_[0]) if on_.size else 0
            tau = t - e0
            if e0 > 0 and 0 <= tau < len(entry_fix["ratio"]):
                v0 = np.asarray(v0, np.float64) / max(entry_fix["ratio"][tau], 0.3)
                p0 = p0 - entry_fix["lag"][tau] * v0
        q_s[k] = torch.from_numpy(p0.astype(np.float32))
        p_s[k] = mass[0, k] * torch.from_numpy(np.asarray(v0, np.float32))
        y_s[k] = float(yaw_d[t, k])
        w = _wrap_q(float(yaw_d[min(t + 1, T - 1), k] - yaw_d[t, k])) if t + 1 < T else 0.0
        L_s[k] = float(I[0, k]) * w
        mode[k] = "sim"
        taint[k] = (int(t), cause, None if other is None else int(other))
        changed.add(k)

    for t in range(TT):
        # ---- entries (boundary condition) --------------------------------------
        if t < T:
            for k in range(N):
                if k in removed or mode[k] != "absent" or pres[t, k] <= 0:
                    continue
                if (pres[:t, k] > 0).any():
                    continue                        # reappearance handled by video mode
                if strict:
                    to_sim(k, t, "entry", None)
                else:
                    mode[k] = "video"

        # ---- influence: decide on the go who must now be simulated ------------
        if t < T and not strict and influence:
            for k in range(N):
                if mode[k] != "video" or pres[t, k] <= 0:
                    continue
                cause = None
                for m in sorted(changed):
                    if m == k:
                        continue
                    if m not in removed and not lost_contact_affected:
                        continue
                    hits = obs_contact.get((k, m))
                    if hits is None:
                        continue
                    since = 0 if m in removed else taint[m][0]
                    nxt = hits[(hits >= t) & (hits >= since)]
                    if nxt.size and nxt[0] - LOOKBACK <= t:
                        cause = ("lost_contact", m)
                        break
                if cause is None:
                    for m in range(N):
                        if mode[m] != "sim" or m == k:
                            continue
                        d = float((torch.from_numpy(pos[t, k]) - q_s[m]).norm())
                        if d - contact[k, m] <= MARGIN:
                            cause = ("new_contact", m)
                            break
                if cause is not None:
                    to_sim(k, t, cause[0], cause[1])

        # ---- the end of the recording: the simulator takes everything ---------
        if t == T - 1 and extend > 0:
            for k in range(N):
                if mode[k] == "video" and pres[t, k] > 0:
                    to_sim(k, t, "video_ended", None)

        # ---- positions this frame ------------------------------------------------
        for k in range(N):
            if mode[k] == "sim":
                P[t, k] = q_s[k].numpy(); M[t, k] = 2
                V[t, k] = (p_s[k] / mass[0, k]).detach().numpy()
            elif mode[k] == "video" and t < T and pres[t, k] > 0:
                P[t, k] = pos[t, k]; M[t, k] = 1
                V[t, k] = vel[t, k]

        # ---- advance the simulated objects one frame ------------------------------
        if t < TT - 1 and law_ctx is not None and any(m_ == "sim" for m_ in mode):
            law_step(t, mode, M, pos, vel, q_s, p_s, mass, law_ctx, N)
            for k in range(N):
                if mode[k] == "sim" and float(q_s[k].abs().max()) > TABLE_EXTENT:
                    mode[k] = "gone"
            continue
        if t < TT - 1 and any(m_ == "sim" for m_ in mode):
            q = torch.zeros(1, N, 2); p = torch.zeros(1, N, 2); act = torch.zeros(1, N)
            yaw = torch.zeros(1, N); L = torch.zeros(1, N)
            for k in range(N):
                if mode[k] == "sim":
                    act[0, k] = 1; q[0, k] = q_s[k]; p[0, k] = p_s[k]; yaw[0, k] = y_s[k]; L[0, k] = L_s[k]
                elif M[t, k] == 1:
                    act[0, k] = 1; q[0, k] = torch.from_numpy(pos[t, k])
                    p[0, k] = mass[0, k] * torch.from_numpy(vel[t, k]); yaw[0, k] = float(yaw_d[t, k])
            p, _ = resolve_voxel(q, p, mass, radius, act, attrs[:N, 1], shapes,
                                 yaw[0].detach().cpu().numpy())
            q, p, yaw, L = model.step_spatial(q, p, yaw, L, mass, radius, e, act, phys, 1.0,
                                              create_graph=False)
            for k in range(N):
                if mode[k] == "sim":
                    q_s[k] = q[0, k].detach(); p_s[k] = p[0, k].detach()
                    y_s[k] = yaw[0, k].detach(); L_s[k] = L[0, k].detach()
                    if float(q_s[k].abs().max()) > TABLE_EXTENT:
                        mode[k] = "gone"

    # ---- events, three detectors, every pair, every frame ---------------------------
    # how sharply each object's velocity changes around each frame (6-frame span)
    kick = np.zeros((TT, N), np.float32)
    if TT > 6:
        kick[3:TT - 3] = np.nan_to_num(np.linalg.norm(V[6:] - V[:-6], axis=-1), nan=0.0)
    events = {"rule": {}, "cal": {}, "kick2": {}, "kick4": {}}
    near = {}
    first_both = {}
    for i in range(N):
        for j in range(i + 1, N):
            if i in removed or j in removed:
                continue
            state = {"rule": [None, False], "cal": [None, False]}
            kstate = {"kick2": False, "kick4": False}
            nl = []
            for t in range(TT):
                if not (np.isfinite(P[t, i]).all() and np.isfinite(P[t, j]).all()):
                    continue
                d = float(np.linalg.norm(P[t, i] - P[t, j]))
                if (i, j) not in first_both:
                    first_both[(i, j)] = t
                gap0 = d - float(contact[i, j])
                for name, a_th in (("kick2", 0.002), ("kick4", 0.004)):
                    inside = kstate[name]
                    if gap0 <= KICK_GAP and not inside:
                        w0, w1 = max(0, t - 3), min(TT, t + 6)
                        if max(kick[w0:w1, i].max(), kick[w0:w1, j].max()) >= a_th:
                            events[name].setdefault((i, j), []).append(t)
                            inside = True
                    elif gap0 > KICK_GAP + RELEASE:
                        inside = False
                    kstate[name] = inside
                for name, scale, th in (("rule", 1.0, THRESH), ("cal", CAL_SCALE, CAL_THRESH)):
                    prev, in_c = state[name]
                    gap = d - scale * float(contact[i, j])
                    if prev is None:
                        state[name] = [d, gap <= th]
                        continue
                    if gap <= th and d < prev and not in_c:
                        events[name].setdefault((i, j), []).append(t)
                        in_c = True
                    elif gap > th + RELEASE:
                        in_c = False
                    state[name] = [d, in_c]
                if d < PREFILTER:
                    yi = float(yaw_d[t, i]) if M[t, i] == 1 else float(y_s[i])
                    yj = float(yaw_d[t, j]) if M[t, j] == 1 else float(y_s[j])
                    g = voxel_gap(shapes[i], float(r[i]), yi, P[t, i], shapes[j], float(r[j]), yj, P[t, j])
                    if g <= NEAR_KEEP:
                        nl.append([int(t), round(g, 2)])
            if nl:
                near[(i, j)] = nl
    return {"T": int(T), "extend": int(extend), "N": int(N), "removed": sorted(removed),
            "taint": taint, "events": events, "near": near, "first_both": first_both,
            "positions": P, "modes": M, "shapes": shapes}


def pair_answer(world, i, j, detector="rule", extend=None, tol=None):
    """Does the stored world contain a collision between i and j?"""
    if i in world["removed"] or j in world["removed"]:
        return False
    a, b = min(i, j), max(i, j)
    limit = world["T"] + (world["extend"] if extend is None else extend)
    if detector in ("rule", "cal"):
        return any(f < limit for f in world["events"][detector].get((a, b), []))
    start = world["first_both"].get((a, b))
    return any(f < limit and f != start and g <= tol for f, g in world["near"].get((a, b), []))
