"""
v8/evaluate.py  —  GENERATED by v8/make_v8.py from v7/evaluate.py. Identical except
the world is simulated by the textbook laws in v8/laws.json. Records have v7's format,
so v7/report.py scores them.
"""
"""
v7/evaluate.py  —  the counterfactual benchmark, one simulated world per intervention
===================================================================================

For each question: remove the object, build ONE counterfactual world with
v7/cf_world.py, and read every choice off that world. Ground truth is never an
answer: collision annotations are not read, the recorded motion is used only
until the intervention can reach an object, and everything after that -- and
everything after the video ends -- is the world model's.

Per choice it writes the events of every detector and every extension, so the
choice of detector and extension length is made on VAL by v7/report.py and
then applied to TEST once.

    python v7/evaluate.py --which val --shard 0 --nshards 4 --out v7/runs/val_A
"""

import argparse
import glob
import json
import os
import sys

import numpy as np
import torch

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
for d in ("src2", "v4", "v5", "v6", "v7"):
    sys.path.insert(0, os.path.join(ROOT, d))

from benchmark_eval import (load_questions, normalise_choices,           # noqa: E402
                            answers_from_conversations, parse_descriptors,
                            program_has, resolve_all, load_split_set, _vid_num)
from world import load_spatial                                           # noqa: E402
import importlib.util                                                    # noqa: E402
_spec = importlib.util.spec_from_file_location("v8_cf_world", os.path.join(HERE, "cf_world.py"))
_cfw = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_cfw)
build_world = _cfw.build_world


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="v6_voxel.pt")
    ap.add_argument("--data", default="data/trajectories_3d_yaw")
    ap.add_argument("--split", default="split3d_yaw.json")
    ap.add_argument("--which", default="val")
    ap.add_argument("--questions",
                    default="zechennlp/counterfactual/validation-00000-of-00001.json")
    ap.add_argument("--extend", type=int, default=60)
    ap.add_argument("--no-lost-affected", action="store_true",
                    help="lost-contact influence only from the REMOVED object (v5's cone)")
    ap.add_argument("--strict", action="store_true",
                    help="simulate every object from the frame it enters")
    ap.add_argument("--no-sim", action="store_true",
                    help="BASELINE: delete the object, keep everyone's recorded motion, "
                         "no simulation, no extension")
    ap.add_argument("--sizes", default=None,
                    help="json of measured per-shape contact sizes (v7/measured_sizes.json)")
    ap.add_argument("--dynamics-sizes", action="store_true",
                    help="with --sizes: the world model also simulates with the measured sizes")
    ap.add_argument("--laws", default=os.path.join(HERE, "laws.json"),
                    help="fitted textbook laws (v8/fit_laws.py)")
    ap.add_argument("--entry-fix", action="store_true",
                    help="correct objects handed to the simulator soon after entering "
                         "(v8/entry_profile.json, fitted on TRAIN)")
    ap.add_argument("--shard", type=int, default=0)
    ap.add_argument("--nshards", type=int, default=1)
    ap.add_argument("--limit", type=int, default=None)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    torch.set_num_threads(1)
    LAWS = json.load(open(a.laws))
    ENTRY = json.load(open(os.path.join(HERE, "entry_profile.json"))) if a.entry_fix else None
    os.makedirs(a.out, exist_ok=True)
    fout = open(os.path.join(a.out, "shard%d.jsonl" % a.shard), "w", encoding="utf-8")

    model = load_spatial(a.model, yaw_known=False)
    files = sorted(glob.glob(os.path.join(a.data, "*.npz")))
    by_num = {_vid_num(f): f for f in files if _vid_num(f) is not None}
    allowed = load_split_set(a.split, a.which)
    rows = load_questions(a.questions)

    worlds = {}
    qn, done = -1, 0
    for row in rows:
        v = _vid_num(str(row.get("video_filename", row.get("video", ""))))
        if v is None or v not in by_num or v not in allowed:
            continue
        qn += 1
        if qn % a.nshards != a.shard:
            continue
        if a.limit and done >= a.limit:
            break
        z = np.load(by_num[v], allow_pickle=True)
        keys = [str(k) for k in z["obj_keys"]]; N = min(8, z["positions"].shape[1])
        qd = parse_descriptors(row.get("program", []))
        if not qd:
            continue
        removed = set(k for k in resolve_all(qd[0], keys) if k < N)
        if not removed:
            continue
        negate = program_has(row.get("program", []), "negate")
        wk = (v, frozenset(removed))
        if wk not in worlds:
            worlds.clear()                          # one video at a time keeps memory flat
            worlds[wk] = build_world(model, z, removed, extend=0 if a.no_sim else a.extend,
                                     lost_contact_affected=not a.no_lost_affected,
                                     strict=a.strict, influence=not a.no_sim,
                                     sizes=json.load(open(a.sizes)) if a.sizes else None,
                                     dynamics_sizes=a.dynamics_sizes, laws=LAWS, entry_fix=ENTRY)
        w = worlds[wk]
        cols = [(int(f), int(x), int(y)) for f, x, y in z["collisions"]]
        choices = normalise_choices(row.get("choices"))
        if choices and all(c["answer"] is None for c in choices):
            answers_from_conversations(row, choices)
        for ci, c in enumerate(choices):
            truth = c["answer"]
            if truth not in ("correct", "wrong"):
                continue
            cd = parse_descriptors(c["program"])
            if len(cd) < 2:
                continue
            h1 = [k for k in resolve_all(cd[0], keys) if k < N]
            h2 = [k for k in resolve_all(cd[1], keys) if k < N]
            if len(h1) != 1 or len(h2) != 1 or h1[0] == h2[0]:
                continue
            i, j = sorted((h1[0], h2[0]))
            rec = {"video": v, "qid": str(row.get("question_id")), "question": row.get("question", ""),
                   "choice": c["choice"], "truth": truth, "negate": bool(negate),
                   "truth_collides": (truth == "correct") != bool(negate),
                   "i": i, "j": j, "removed": sorted(removed), "T": w["T"],
                   "participant_removed": bool(i in removed or j in removed),
                   "taint_i": w["taint"].get(i), "taint_j": w["taint"].get(j),
                   "rule": w["events"]["rule"].get((i, j), []),
                   "cal": w["events"]["cal"].get((i, j), []),
                   "kick2": w["events"]["kick2"].get((i, j), []),
                   "kick4": w["events"]["kick4"].get((i, j), []),
                   "near": w["near"].get((i, j), []),
                   "first_both": w["first_both"].get((i, j)),
                   # annotations, for DIAGNOSIS ONLY -- never used to answer
                   "diag_obs_frames": [f for f, x, y in cols if {x, y} == {i, j}]}
            fout.write(json.dumps(rec) + "\n")
        fout.flush()
        done += 1
        print("shard %d  q %d  video %d  sim objects %d" % (a.shard, done, v, len(w["taint"])), flush=True)
    fout.close()


if __name__ == "__main__":
    main()
