"""
v8/make_v8.py  —  build v8/cf_world.py and v8/evaluate.py from v7's files
=========================================================================

v8 differs from v7 in exactly ONE thing: the simulator. v7 advances simulated
objects with the learned world model (voxel bounces + learned energy + learned
friction); v8 advances them with the textbook laws fitted in v8/laws.json.

Everything else -- when objects start being simulated, entries, running past the
end of the video, every collision detector, object sizes used for detection --
must stay byte-for-byte what v7 does, or a score difference could not be
attributed. So v8's files are GENERATED from v7's by inserting code at anchors
that must each appear exactly once; nothing of v7's is retyped.

    python v8/make_v8.py
"""

import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

LAW_CODE = '''
# ============================================================================
# v8: THE TEXTBOOK-LAW SIMULATOR (replaces the learned world model's step)
# ============================================================================
LAW_GAP_DEFAULT = 0.01


def make_law_context(z, shapes, N, laws):
    """Per-object facts the laws need: material, kind, contact size."""
    keys = [str(k) for k in z["obj_keys"]][:N]
    mats = [k.split("_")[1] for k in keys]
    col = laws["collision"]
    return {"mats": mats, "kinds": ["%s/%s" % (shapes[k], mats[k]) for k in range(N)],
            "sizes": np.array([laws["contact_sizes"][shapes[k]] for k in range(N)], np.float64),
            "motion": laws["motion"], "ratio": float(col["mass_ratio"]), "e": col["e"],
            "mu": float(col["mu"]), "gap": float(laws.get("contact_gap", LAW_GAP_DEFAULT))}


def law_step(t, mode, M, pos, vel, q_s, p_s, mass, ctx, N):
    """One frame for every simulated object, by the fitted laws.

    1. BOUNCE: every approaching pair whose surfaces are within ctx['gap'] gets
       the textbook impulse along the line of centres, J = -(1+e)(v_rel.n) /
       (1/m_i + 1/m_j), plus sliding friction at the contact. Equal and
       opposite, so momentum is conserved. Objects still following the video
       take part (their own recorded motion is not overwritten).
    2. MOTION LAW: each simulated object's speed shrinks by its kind's law --
       a fixed amount per frame (sliding) or a fixed percentage (rolling).
    3. MOVE: position += velocity.
    """
    idx = [k for k in range(N) if mode[k] == "sim" or M[t, k] == 1]
    P, V = {}, {}
    for k in idx:
        if mode[k] == "sim":
            P[k] = q_s[k].numpy().astype(np.float64)
            V[k] = (p_s[k] / mass[0, k]).detach().numpy().astype(np.float64)
        else:
            P[k] = pos[t, k].astype(np.float64)
            V[k] = vel[t, k].astype(np.float64)
    sizes, mats = ctx["sizes"], ctx["mats"]
    for a in range(len(idx)):
        for b in range(a + 1, len(idx)):
            i, j = idx[a], idx[b]
            if mode[i] != "sim" and mode[j] != "sim":
                continue
            d = P[i] - P[j]
            dist = float(np.linalg.norm(d))
            if dist < 1e-9 or dist - (sizes[i] + sizes[j]) > ctx["gap"]:
                continue
            vrel = V[i] - V[j]
            if float(vrel @ d) >= 0:
                continue
            n = d / dist
            vn = float(vrel @ n)
            mi = ctx["ratio"] if mats[i] == "metal" else 1.0
            mj = ctx["ratio"] if mats[j] == "metal" else 1.0
            cls = "".join(sorted(("m" if mats[i] == "metal" else "r") + ("m" if mats[j] == "metal" else "r")))
            e = float(ctx["e"][cls])
            inv = 1.0 / mi + 1.0 / mj
            Jn = -(1.0 + e) * vn / inv
            V[i] = V[i] + (Jn / mi) * n
            V[j] = V[j] - (Jn / mj) * n
            if ctx["mu"] > 0:
                vt = vrel - vn * n
                vtn = float(np.linalg.norm(vt))
                if vtn > 1e-12:
                    tv = vt / vtn
                    Jt = min(ctx["mu"] * Jn, vtn / inv)
                    V[i] = V[i] - (Jt / mi) * tv
                    V[j] = V[j] + (Jt / mj) * tv
    for k in idx:
        if mode[k] != "sim":
            continue
        L = ctx["motion"].get(ctx["kinds"][k], {"chosen": "const", "param": 0.0})
        v = V[k]
        if L["chosen"] == "exp":
            v = v * (1.0 - L["param"])
        elif L["chosen"] == "coul":
            s = float(np.linalg.norm(v))
            v = v * (max(s - L["param"], 0.0) / max(s, 1e-12))
        q_s[k] = torch.from_numpy((P[k] + v).astype(np.float32))
        p_s[k] = mass[0, k].detach() * torch.from_numpy(v.astype(np.float32))


'''

WORLD_DOC = '''"""
v8/cf_world.py  —  v7's "what if" world builder, simulated by TEXTBOOK LAWS
===========================================================================
GENERATED by v8/make_v8.py from v7/cf_world.py. Identical to v7 except the
simulator: pass laws=json.load(open("v8/laws.json")) and every simulated object
is advanced by the fitted laws (law_step) instead of the learned world model.
Without laws=... it behaves exactly like v7. v7's own description follows.
"""
'''


def once(text, anchor, what):
    n = text.count(anchor)
    if n != 1:
        raise SystemExit("anchor for %s found %d times, expected 1" % (what, n))


def build_world_file():
    src = open(os.path.join(ROOT, "v7", "cf_world.py"), encoding="utf-8").read()
    sig_old = "influence=True, sizes=None, dynamics_sizes=False):"
    sig_new = "influence=True, sizes=None, dynamics_sizes=False, laws=None, entry_fix=None):"
    ctx_anchor = "    contact = r[:, None] + r[None, :]\n"
    step_anchor = "        # ---- advance the simulated objects one frame ------------------------------\n"
    def_anchor = "def build_world(model, z, removed"
    tosim_anchor = ("        q_s[k] = torch.from_numpy(pos[t, k])\n"
                    "        p_s[k] = mass[0, k] * torch.from_numpy(np.asarray(v0, np.float32))\n")
    tosim_new = ("        p0 = pos[t, k].astype(np.float64)\n"
                 "        if entry_fix is not None:\n"
                 "            # an object still sliding into view is measured too SLOW and too far AHEAD\n"
                 "            # (the visible part's centre): undo both with the TRAIN entry profile\n"
                 "            on_ = np.where(pres[:, k] > 0)[0]\n"
                 "            e0 = int(on_[0]) if on_.size else 0\n"
                 "            tau = t - e0\n"
                 "            if e0 > 0 and 0 <= tau < len(entry_fix[\"ratio\"]):\n"
                 "                v0 = np.asarray(v0, np.float64) / max(entry_fix[\"ratio\"][tau], 0.3)\n"
                 "                p0 = p0 - entry_fix[\"lag\"][tau] * v0\n"
                 "        q_s[k] = torch.from_numpy(p0.astype(np.float32))\n"
                 "        p_s[k] = mass[0, k] * torch.from_numpy(np.asarray(v0, np.float32))\n")
    for a, w in ((sig_old, "signature"), (ctx_anchor, "contact line"), (step_anchor, "advance block"),
                 (def_anchor, "build_world definition"), (tosim_anchor, "to_sim start state")):
        once(src, a, w)
    src = src.replace(sig_old, sig_new)
    src = src.replace(tosim_anchor, tosim_new)
    src = src.replace(ctx_anchor, ctx_anchor +
                      "    law_ctx = make_law_context(z, shapes, N, laws) if laws is not None else None\n")
    src = src.replace(step_anchor, step_anchor +
                      "        if t < TT - 1 and law_ctx is not None and any(m_ == \"sim\" for m_ in mode):\n"
                      "            law_step(t, mode, M, pos, vel, q_s, p_s, mass, law_ctx, N)\n"
                      "            for k in range(N):\n"
                      "                if mode[k] == \"sim\" and float(q_s[k].abs().max()) > TABLE_EXTENT:\n"
                      "                    mode[k] = \"gone\"\n"
                      "            continue\n")
    src = src.replace(def_anchor, LAW_CODE.lstrip("\n") + def_anchor)
    open(os.path.join(ROOT, "v8", "cf_world.py"), "w", encoding="utf-8").write(WORLD_DOC + src)


def build_eval_file():
    src = open(os.path.join(ROOT, "v7", "evaluate.py"), encoding="utf-8").read()
    imp_old = "from cf_world import build_world                                         # noqa: E402\n"
    imp_new = ("import importlib.util                                                    # noqa: E402\n"
               "_spec = importlib.util.spec_from_file_location(\"v8_cf_world\", os.path.join(HERE, \"cf_world.py\"))\n"
               "_cfw = importlib.util.module_from_spec(_spec)\n"
               "_spec.loader.exec_module(_cfw)\n"
               "build_world = _cfw.build_world\n")
    arg_old = "    ap.add_argument(\"--shard\", type=int, default=0)\n"
    arg_new = ("    ap.add_argument(\"--laws\", default=os.path.join(HERE, \"laws.json\"),\n"
               "                    help=\"fitted textbook laws (v8/fit_laws.py)\")\n"
               "    ap.add_argument(\"--entry-fix\", action=\"store_true\",\n"
               "                    help=\"correct objects handed to the simulator soon after entering \"\n"
               "                         \"(v8/entry_profile.json, fitted on TRAIN)\")\n" + arg_old)
    thr_old = "    torch.set_num_threads(1)\n"
    thr_new = thr_old + ("    LAWS = json.load(open(a.laws))\n"
                         "    ENTRY = json.load(open(os.path.join(HERE, \"entry_profile.json\"))) if a.entry_fix else None\n")
    call_old = "                                     dynamics_sizes=a.dynamics_sizes)"
    call_new = "                                     dynamics_sizes=a.dynamics_sizes, laws=LAWS, entry_fix=ENTRY)"
    for a, w in ((imp_old, "import"), (arg_old, "--shard arg"), (thr_old, "thread line"), (call_old, "build_world call")):
        once(src, a, w)
    src = src.replace(imp_old, imp_new).replace(arg_old, arg_new).replace(thr_old, thr_new).replace(call_old, call_new)
    doc = ('"""\nv8/evaluate.py  —  GENERATED by v8/make_v8.py from v7/evaluate.py. Identical except\n'
           'the world is simulated by the textbook laws in v8/laws.json. Records have v7\'s format,\n'
           'so v7/report.py scores them.\n"""\n')
    open(os.path.join(ROOT, "v8", "evaluate.py"), "w", encoding="utf-8").write(doc + src)


if __name__ == "__main__":
    build_world_file()
    build_eval_file()
    print("wrote v8/cf_world.py and v8/evaluate.py")
